### ISSUE TITLE
Version Conflict / Missing DB files

### ISSUE THREAD

**Issue by klyxmaster** [mangosArchives/Mangos-Zero-server-old#24]
Not a noob, been doing this since 2005.
I been running zero for 2yrs now.. very nicely done. clean and well kept. I just recently updated again. and lots of errors.
These are easily fixed if the db files were included.

[A] You have: --> 'z1765_xxxxx_01_mangos_spell_affect.sql'
[B] You need --> 'z1824_xxxxx_01_mangos_spell_affect_event.sql'

These are old easy errors to fix, however the recent database:
https://github.com/mangos-zero/database
does not have any of these files. Where are they?

I did try using the fulldb but it gave a diffeent [A]/[B] error.

The recent Rev (today i did it 8.19.12) is 1837
The one that is working flawlessly is 1765

Is there a link for the DB files up to 1837?

Thanks

**Comment by sethallenford** [comment]
that is such a good question I'm in his situation too!

**Comment by klyxmaster** [comment]
well if you dont get a reply soon, and you dont mind 1765, i can zip it and send it to you.. works fine.. I looked at the tweaks they did, nothing major but i just wanted to stay up to date

**Comment by sethallenford** [comment]
Please do and btw can you just send me all of your SQL databases too while you're at it if you don't mind?

**Comment by sethallenford** [comment]
I had mangos up and running with NPC's and their AI 2 different times a while back and now... I just forgot and I'm kinda tired of trying to get it to work!

**Comment by sethallenford** [comment]
Maybe make a repo? Just for me to DL all of your databases as of Revision 1765 :)

**Comment by sethallenford** [comment]
But if you can get me your 1765 Revision in a zip I would be greatly appreciated! I would really really appreciate that bro, if you could just give me a zip file of 1765 I would be a happy guy. You don't have to bother getting me all your databases if its too work :)

**Comment by klyxmaster** [comment]
here try this 
http://rustycraft.sytes.net/downloads/!SERVER.7z

sorry for the delay, i have like 3 servers im working on and helping a few others. this new update log jammed me, so had to put 1765 back up.
the 7z file has server and db... i left out the other stuff as i am sure you have it.
Lemme know if you get this, so i can delete this, as im sure the mod would not care for this. but then missing files are not cool either.

**Comment by sethallenford** [comment]
Wouldn't happen to have the src file so I can rebuild 1765 from scratch would ya? Btw your'e awesome the transfer worked great!

**Comment by klyxmaster** [comment]
I believe this is the the one.. had it backed up on another system.

http://rustycraft.sytes.net/downloads/mangos_zero_1765_sourcecode.7z

**Comment by klyxmaster** [comment]
o btw that one has playerbots... fun addon..if you havent noticed and they work

**Comment by ghost** [comment]
Try using the current zero-database from @mangos-zero/database. It has all the required updates.

**Comment by klyxmaster** [comment]
https://github.com/mangos-zero/database.git
thats the only one I could find
spell_effect.sql is not in the list

**Comment by ghost** [comment]
Try using the version from today, it will work.

**Comment by sethallenford** [comment]
can't get it to work for me... STILL!

SQL: SELECT required_z1765_xxxxx_01_mangos_spell_affect FROM db_version LIMIT 1
2012-08-19 17:17:07 ERROR:query ERROR: Unknown column 'required_z1765_xxxxx_01_mangos_spell_affect' in 'field list'
2012-08-19 17:17:07 ERROR:The table `db_version` in your [WORLD] database indicates that this database is out of date!
2012-08-19 17:17:07 ERROR:
2012-08-19 17:17:07 ERROR:  [A] You have: --> `z1809_xxxxx_01_mangos_spell_affect_event.sql`
2012-08-19 17:17:07 ERROR:
2012-08-19 17:17:07 ERROR:  [B] You need: --> `z1765_xxxxx_01_mangos_spell_affect.sql`
2012-08-19 17:17:07 ERROR:
2012-08-19 17:17:07 ERROR:You must apply all updates after [A] to [B] to use mangos with this database.
2012-08-19 17:17:07 ERROR:These updates are included in the sql/updates folder.
2012-08-19 17:17:07 ERROR:Please read the included [README] in sql/updates for instructions on updating.

Im just totally confused on how to update mangos I don't understand when it says update everything in between in sql/updates because when I do it just doesn't work is there a way I could get your working database copy via a Zip/rar file from you Luda? I been working on this just for too long and Im ready to get some help =(

**Comment by sethallenford** [comment]
1765 works fine for me but man I can't get 1809 to work...

I just would really like your working database and them develop from there. That would be a dream come true =)

**Comment by ghost** [comment]
You have to use the develop branch for mangos, scriptdev0 and database. I just did a fresh checkout, and it works.

**Comment by sethallenford** [comment]
Yeah I forgot to respond I got 1824 up and running very easily. Ty so much for your help!

**Comment by sethallenford** [comment]
Now I need to figure out how to get the Scarlet Monastery Corrupted Ashbringer event to work...
